disabled_rules:
   - control_statement
   - trailing_whitespace
   - force_cast
   - force_unwrapping
   - force_try
   - large_tuple
   - redundant_string_enum_value
line_length:
    ignores_comments: true
